###
GET http://127.0.0.1:2333/search/t/1
User-Agent: insomnia/9.3.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjAzNTg0MTh9.ija5oFocvDyBd-GgH2pZNLJSWAGR6zuDpqK6xhFIIrs

###
GET http://127.0.0.1:2333/goals
User-Agent: insomnia/9.3.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjAzNTg0MTh9.ija5oFocvDyBd-GgH2pZNLJSWAGR6zuDpqK6xhFIIrs

###
POST http://127.0.0.1:2333/goals/create
Content-Type: application/json
User-Agent: insomnia/9.3.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjAzNTg0MTh9.ija5oFocvDyBd-GgH2pZNLJSWAGR6zuDpqK6xhFIIrs

{
  "EndTime": "2024-07-24T15:06:17.173Z",
  "Title": "Comprar uma casa",
  "TargetedValue": 120000,
  "Value": 10000
}

###
GET http://127.0.0.1:2333/transaction
User-Agent: insomnia/9.3.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjAzNTg0MTh9.ija5oFocvDyBd-GgH2pZNLJSWAGR6zuDpqK6xhFIIrs

###
DELETE http://127.0.0.1:2333/transaction/delete/
User-Agent: insomnia/9.3.2

###
PUT http://127.0.0.1:2333/transaction/update/80dbf4c1-68b9-44ff-899c-9d27a04a1245
Content-Type: application/json
User-Agent: insomnia/9.3.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjAzNTg0MTh9.ija5oFocvDyBd-GgH2pZNLJSWAGR6zuDpqK6xhFIIrs

{
  "Type": "SAL"
}

###
POST http://127.0.0.1:2333/transaction/create
Content-Type: application/json
User-Agent: insomnia/9.3.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjAzNTg0MTh9.ija5oFocvDyBd-GgH2pZNLJSWAGR6zuDpqK6xhFIIrs

{
  "Title": "Fatura do Carro",
  "Value": 350,
  "Type": "SAL",
  "accountId": "a8245ab6-626b-4a8e-a67a-b91138fd4d49"
}

###
DELETE http://127.0.0.1:2333/account/delete/
User-Agent: insomnia/9.3.2

###
GET http://127.0.0.1:2333/account/view/a8245ab6-626b-4a8e-a67a-b91138fd4d49
User-Agent: insomnia/9.3.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjAzNTg0MTh9.ija5oFocvDyBd-GgH2pZNLJSWAGR6zuDpqK6xhFIIrs

###
POST http://127.0.0.1:2333/account/register
Content-Type: application/json
User-Agent: insomnia/9.2.0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjAzNTg0MTh9.ija5oFocvDyBd-GgH2pZNLJSWAGR6zuDpqK6xhFIIrs

{   
  "Name": "Familia",
  "Value": 0
}

###
GET http://127.0.0.1:2333/users/account
User-Agent: insomnia/9.3.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjExNDEwMjZ9.A1t6-0DvGzJCwRsXfcxVS7Wi8mv210vOdKKz9CXEVbk

###
GET http://127.0.0.1:2333/auth/profile
User-Agent: insomnia/9.2.0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUwOTNkYi0yM2JmLTRjMjEtOTA5MC0xMzhhMGE0Y2ZkNjciLCJpYXQiOjE3MjExNDEwMjZ9.A1t6-0DvGzJCwRsXfcxVS7Wi8mv210vOdKKz9CXEVbk

###
POST http://127.0.0.1:2333/users/register
Content-Type: application/json
User-Agent: insomnia/9.2.0

{   
  "Email": "dev@gmail.com",
  "Senha": "admin",
  "UsernName": "thierrir Alencar"
}

###
PATCH http://127.0.0.1:2333/auth/login
Content-Type: application/json
User-Agent: insomnia/9.2.0

{
  "Email": "dev@gmail.com",
  "Senha": "admin"
}