POST http://127.0.0.1:2333/users/register HTTP/1.1
content-type: application/json

{   
    "Email":"CiringaMen@gmail.com",
    "Senha":"CiringaBigCock",
    "UsernName":"thierrir Alencar"
}
###

POST http://127.0.0.1:2333/account/register HTTP/1.1
content-type: application/json

{   
    "Name":"Test Creepy Account",
    "Value":600,
    "userId":"7e2757bc-5d31-4a76-b44e-a53b9aad9879"
}